### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by eridanusdev** [VizzleTF/GeminiCommit#1]
Hi Vizzle, I'm using your Gemini Commit extension to generate commit messages with Gemini AI. I was wondering if it would be possible to add a feature that allows the extension to only generate commit messages after the changes have been staged. This would be really helpful for me as it would allow me to review the changes before generating a commit message. At the moment, I am only able to generate the message after changes. Thanks for considering my request!

**Comment by VizzleTF** [comment]
Hi Eridanus, glad to hear you're using GeminiCommit. I've added a new feature in version 1.6.0 of the extension. Simply update it through the marketplace and you'll find a new option in settings to generate messages only for staged changes.

**Comment by eridanusdev** [comment]
Hi Vizzle,

I can't say just how grateful I am for this. Keep doing the good work, sir.

**Comment by VizzleTF** [comment]
> Hi Vizzle,
> 
> I can't express how grateful I am. Keep up the good work.

Hi Eridanus,
I've updated the logic of extension:
- If there are staged changes - the extension processes only those
- If there are no staged changes - the extension processes all changes

So you can uncheck this option and use extesion both way

**Comment by eridanusdev** [comment]
Oh, okay sir. Once again, thank you soo much.
