### ISSUE TITLE
Always get same result

### ISSUE THREAD

**Issue by Hexi1997** [VizzleTF/GeminiCommit#2]
fix: Corrected data validation errors
Improved input sanitization routines
Enhanced error handling mechanisms

**Comment by Hexi1997** [comment]
OK, I found the problem. If I don't execute `git add .`, I can get the correct result. Why doesn't the plugin read the stashed files by default? This is in line with normal operation logic.

**Comment by VizzleTF** [comment]
Hi Hexi,
There were two issues with the extension:

The extension was only using `git diff` functionality, which doesn't show newly added files.
When the onlyStaged checkbox was unchecked in settings, the extension was ignoring staged changes. I've updated the logic:
- If there are staged changes - the extension processes only those
- If there are no staged changes - the extension processes all changes


I've fixed both issues in the GitService class. Version 1.6.3 includes these fixes - please update the extension and everything should work correctly.
Thanks for highlighting these issues!

**Comment by VizzleTF** [comment]
Please feel free to reopen this issue or open a new issue if you encounter any problems with the updated version.

**Comment by Hexi1997** [comment]
> Hi Hexi, 嗨河西， There were two issues with the extension:扩展有两个问题：
> 
> The extension was only using `git diff` functionality, which doesn't show newly added files.该扩展程序仅使用 `git diff` 功能，不显示新添加的文件。 When the onlyStaged checkbox was unchecked in settings, the extension was ignoring staged changes. I've updated the logic:当设置中取消选中 onlyStaging 复选框时，扩展程序将忽略暂存的更改。我更新了逻辑：
> 
> * If there are staged changes - the extension processes only those如果存在分阶段更改 - 扩展程序仅处理那些
> * If there are no staged changes - the extension processes all changes如果没有分阶段更改 - 扩展程序将处理所有更改
> 
> I've fixed both issues in the GitService class. Version 1.6.3 includes these fixes - please update the extension and everything should work correctly.我已经在 GitService 类中解决了这两个问题。版本 1.6.3 包含这些修复 - 请更新扩展，一切都应该正常工作。 Thanks for highlighting these issues!感谢您强调这些问题！

Thank you, well done.
